### ISSUE TITLE
ok, where do you get opencv 4.4 for the jetson nano?

### ISSUE THREAD

**Issue by JVTEAM** [tomek-l/ai-thermometer#1]
I have 4.1 from jetsonhacks.

**Comment by tomasz-lewicki** [comment]
Hi there!

Check this out:
[https://github.com/mdegans/nano_build_opencv/blob/master/build_opencv.sh](https://github.com/mdegans/nano_build_opencv/blob/master/build_opencv.sh)

**Comment by tomasz-lewicki** [comment]
Also starting with 51a6d427ab5c2ab166f3f4abe8e51ca4293a1883 the code will work with older versions of OpenCV, including 4.1.

Older OpenCV versions don't have CUDA support. The code will work, but will be much slower (I got ~3FPS instead of 17FPS). The IR inference will still work at 9FPS.

@JVTEAM  let me know if I that answers your question.
