### ISSUE TITLE
White box on RGB Camera out of sync with IR Camera

### ISSUE THREAD

**Issue by aaronf99** [tomek-l/ai-thermometer#19]
Hello,
I have copied your project directly, using the same casing. After running the program, I can see that the frame of reference is off. Is there a fix for this?
![Image-2](https://user-images.githubusercontent.com/19917418/101173268-33344a00-363a-11eb-95ea-79ce6be16b7b.jpeg)
![Image-3](https://user-images.githubusercontent.com/19917418/101173271-33cce080-363a-11eb-993f-d9667e99f80a.jpeg)
![Image](https://user-images.githubusercontent.com/19917418/101173280-36c7d100-363a-11eb-88fc-078120a5b4a3.jpeg)
![Image-1](https://user-images.githubusercontent.com/19917418/101173283-392a2b00-363a-11eb-8378-77e9f33f72dd.jpeg)

**Comment by tomasz-lewicki** [comment]
Hi there, @aaronf99 !

Yup, that's a bug. I was experimenting with a different RGB camera with a wider FOV and merged code to master, but the publicly available hardware for that is not yet updated. In the future, the system will support multiple cameras with different FOVs. I will probably also start a "stable" branch to avoid issues like that in the future.

**Comment by aaronf99** [comment]
Thanks for the reply @tomek-l 

That makes sense, I am using the Raspberry Pi Camera Module V2.
Is there a quick fix I can do for this as the area that I currently work in could really do with this right now.

Many Thanks,
Aaron

**Comment by tomasz-lewicki** [comment]
Hi @aaronf99!

e2fc37707c8f44a0c80dae196fccdb94971e0f23 introduces a hotfix for this bug. Checkout the newest master, and let me know if that looks better. 

The alignment could still be a bit off at a distance. The reason is the way the sensor is attached to Raspberry Pi CM V2.1 PCB (double sided tape). Due to that the RGB sensor will be mounted at a slightly different angle in different units (that's why I'm experimenting with a different cameras in the first place). I will also work out support for cameras with different FOVs in a future version.
